name: Deploy with rsync

on:
  #push:
    #branches:
      #- main
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      - self-hosted
      - web-sms-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify dependencies on runner
        run: |
          echo "📦 Vérification de rsync et ssh sur le runner Rocky..."
          which rsync || (echo "❌ rsync manquant !" && exit 1)
          which ssh || (echo "❌ ssh manquant !" && exit 1)
          echo "✅ Dépendances OK"

      - name: Run pre-deploy checks
        run: |
          echo "🧪 Running checks..."
          # Exemple : tests / build
          echo "✅ Checks passed"

  check-ssh:
    runs-on: 
      - self-hosted
      - web-sms-2
    needs: build
     
    steps:
      - name: Check SSH connection and deploy files
        run: |
          echo "🔑 Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT_W }} \
            -i ~/.ssh/id_ed25519 \
            ${{ vars.DEPLOY_USER_W }}@${{ secrets.DEPLOY_HOST_W }} "echo ✅ Connected to remote Ubuntu"

  rsync-deploy:
    runs-on: 
      - self-hosted
      - web-sms-1
    needs: check-ssh
    steps:
      - name: Rsync files to remote server
        run: |
          echo "📦 Deploying files with rsync..."
          rsync -avzr --delete --progress \
            -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT_W }} -i ~/.ssh/id_ed25519" \
            ./ \
            ${{ vars.DEPLOY_USER_W }}@${{ secrets.DEPLOY_HOST_W }}:${{ secrets.DEPLOY_PATH_W }}
            
  docker-compose-deploy:
    runs-on: 
      - self-hosted
      - web-sms-2
    needs: rsync-deploy
    steps:
      - name: Run Docker Compose on remote server
        run: |
          echo "🐳 Starting Docker Compose on remote server..."
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT_W }} \
            -i ~/.ssh/id_ed25519 \
            ${{ vars.DEPLOY_USER_W }}@${{ secrets.DEPLOY_HOST_W }} \
            "
              cd ${{ secrets.DEPLOY_PATH_L }} && \
              cat .env.websms-app .env.websms-db .env.websms-migration .env.websms-minio > .env && \
              docker compose -f compose.yml up -d
            "

  docker-compose-verify:
    runs-on:
      - self-hosted
      - web-sms-1
    needs: docker-compose-deploy
    steps:
      - name: Verify Docker Compose containers
        run: |
          echo "🔍 Vérification des containers Docker..."
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT_W }} \
            -i ~/.ssh/id_ed25519 \
            ${{ vars.DEPLOY_USER_W }}@${{ secrets.DEPLOY_HOST_W }} \
            "
              cd ${{ secrets.DEPLOY_PATH_L }} && \
              docker compose -f compose.yml ps
            "
